package dev.blue.jcomp;

public enum TokenType {
	OPEN, CLOSE, OPERATOR, KEYWORD, DEFINED, TYPE, SYMBOL, COMMENT, BREAK, STRING, CONTENTS, SEQUENCER, COMPARATOR, PRIVACY, ACCESS, NONE//FUNC, STRUCT, FIELD, TYPE, NUM, STRING, BINARY, 
}
